version: '3.8'

services:
  postgres:
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./product-algorithms-volume:/var/lib/postgresql/data
    networks:
      - product_algorithms_network

networks:
  product_algorithms_network:
    driver: bridge
volumes:
  product-algorithms-volume: